### ISSUE TITLE
fails to build with ITK 4.4 

### ISSUE THREAD

**Issue by gerddie** [ANTsX/ANTs#24]
Compile error: 

In file included from ANTs/Examples/CompositeTransformUtil.cxx:12:0:
ANTs/Examples/../Utilities/itkantsReadWriteTransform.h: In function 'typename itk::Transform<TScalar, NDimensions, NDimensions>::Pointer itk::ants::ReadTransform(const string&, bool)':
ANTs/Examples/../Utilities/itkantsReadWriteTransform.h:70:19: error: 'TransformFileReaderTemplate' in namespace 'itk' does not name a type
